ViewComponentExample/ViewComponentExample/Models/Person.cs
namespace ViewComponentExample.Models
{
    public class Person
    {
        public string  ? PersonName { get; set; }
        public string  ? JobTitle { get; set; }
        
    }
}

ViewComponentExample/ViewComponentExample/Models/PersonGridModel.cs
namespace ViewComponentExample.Models
{
    public class PersonGridModel
    {
        public string GridTitle { get; set; }=string.Empty;
        public List<Person> Person { get; set; } = new List<Person>(); 
    }
}

ViewComponentExample/ViewComponentExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentExample.Models;

namespace ViewComponentExample.Controllers
{
    public class HomeController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/about")]
        public IActionResult About()
        {
            return View();
        }
        
        [Route("friends-list")]
        public IActionResult LoadFriendsList()
        {
            PersonGridModel personGridModel = new PersonGridModel()
            {
                GridTitle = "Persons List",
                Person = new List<Person>() {
                    new Person() { PersonName="Shambhu",JobTitle="Software Developer"},
                    new Person() { PersonName="Sagar",JobTitle="Teacher"}
                }
            };

            return ViewComponent("Grid", new { grid=personGridModel });
        }


    }
}

ViewComponentExample/ViewComponentExample/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentExample.Models;

namespace ViewComponentExample.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
     public async  Task<IViewComponentResult> InvokeAsync(PersonGridModel grid)
        {
           
             return View("Default",grid); 
            // this view searches the partial location invoked a partial view Views/Shared/Component/Grid/Default.cshtml     
        }
    }
}

ViewComponentExample/ViewComponentExample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";

}

<h1>About</h1>
<p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    It has survived not only five centuries, but also the leap into electronic typesetting, remaining
    essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
    Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including
    versions of Lorem Ipsum.
</p>
@await Component.InvokeAsync("Grid")

<vc:grid></vc:grid>

ViewComponentExample/ViewComponentExample/Views/Home/Index.cshtml
@{
    ViewBag.title = "Home";
}

<h1>Home</h1>

<button class="button button-blue-back" id="load-friends-button">Load Friends</button>
<div id="list">

</div>
<script src="~/friends.js"></script>

ViewComponentExample/ViewComponentExample/Views/Shared/Components/Grid/Default.cshtml

@model PersonGridModel
<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Symbol Number</th>
                <th>Name</th>
            </tr>
        </thead>

        @foreach(Person person in Model.Person)
        {
            <tbody>
            <tr>
                <td>@person.PersonName</td>
                <td>@person.JobTitle</td>
            </tr>
            
          </tbody> 
        }
       
    </table>
</div>

ViewComponentExample/ViewComponentExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>

    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">View Components Demo App</div>
            <ul>
            <li><a href="~/">Home</a></li>
            <li><a href="~/about">About</a></li>
            </ul>
           
        </div>
    </div>
    <div class="page-content">
        @RenderBody()
    </div>
</body>
</html>